# NumPy Functions : 

In [2]:
import numpy as np

# Arange()

In [3]:
# np.arange(start,end,steps)
array_1d=np.arange(1,13)
print(array_1d)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [4]:
array_even=np.arange(1,13,2)
print(array_even)

[ 1  3  5  7  9 11]


# linspace()

In [5]:
np.linspace(1,5,4)

array([1.        , 2.33333333, 3.66666667, 5.        ])

# Reshape()

In [6]:
ar_2d=array_1d.reshape(2,6)
print(ar_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [7]:
ar_3d=array_1d.reshape(2,3,2)
print(ar_3d)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# ravel()

In [8]:
ar_3d.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# flatten

In [9]:
ar_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

# Transpose

In [11]:
ar_3d.transpose()
ar_3d.T

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])