In [1]:
import numpy as np

In [4]:
array_1=np.arange(1,10).reshape(3,3)
array_2=np.arange(1,10).reshape(3,3)
print(array_1)
print(array_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# Element wise addition
array_1+array_2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
np.add(array_1,array_2)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [7]:
# Element wise substraction
array_1-array_2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
np.subtract(array_1,array_2)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
# Element wise division
array_1/array_2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.divide(array_1,array_2)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
# Element wise multiplication
array_1*array_2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [12]:
np.multiply(array_1,array_2)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [15]:
print(array_1)
print(array_2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
# Row column wise

# Given vectors a = [1, 2, 3] and b = [4, 5, 6], the dot product (a · b) is calculated as:

# (a · b) = 1 * 4 + 2 * 5 + 3 * 6 = 4 + 10 + 18 = 32

array_1@array_2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [19]:
array_1.dot(array_2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [20]:
# Find max value from an array
array_1.max()

9

In [21]:
# What is index of max value
array_1.argmax()

8

In [25]:
# what is max value of array in the column wise oe row wise
# 0=column in height
# 1=row in width
array_1.max(axis=1)

array([3, 6, 9])

In [26]:
# minimum value in array
array_1.min()

1

In [27]:
array_1.min(axis=1)

array([1, 4, 7])

In [28]:
array_1.argmin()

0

In [31]:
# Sum of all elements in array
array_1.sum()

array([ 6, 15, 24])

In [34]:
array_1.sum(axis=0)

array([12, 15, 18])

In [35]:
array_1.sum(axis=1)

array([ 6, 15, 24])

In [37]:
# First sum all values in array then divide it with the number of elements in array
np.mean(array_1)

5.0

In [38]:
np.sqrt(array_1)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [40]:
np.std(array_1)

2.581988897471611

In [41]:
np.exp(array_1)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [42]:
np.log(array_1)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])