In [3]:
import numpy as np

In [4]:
array_1d=np.array([1,2,3,4]) #1 Array
print(array_1d)

[1 2 3 4]


In [5]:
type(array_1d)

numpy.ndarray

In [6]:
array_1d.ndim

1

In [8]:
#Creating 2D array
array_2d=np.array([[1,2,3,4],[6,3,8,2]])
print(array_2d)

[[1 2 3 4]
 [6 3 8 2]]


In [9]:
# Check its 2d 1d or 3d
array_2d.ndim

2

In [10]:
# How many elements in our arrat
array_2d.size

8

In [11]:
array_1d.size

4

In [12]:
# Check array Shape
array_2d.shape

(2, 4)

In [13]:
# (row,column)

In [15]:
array_1d.dtype

dtype('int64')