In [2]:
import numpy as np
import random

In [7]:
np.random.random(1)

array([0.66895204])

In [10]:
# 2d array with random finction
np.random.random((3,3))

array([[0.1783436 , 0.68118495, 0.31300817],
       [0.00887745, 0.2821666 , 0.31643574],
       [0.94877498, 0.23551474, 0.00888165]])

In [90]:
# Random number
np.random.randint(1,100)

12

In [91]:
np.random.randint(1,100,(3,3))

array([[32, 23,  6],
       [46, 26, 69],
       [76, 88, 33]])

In [95]:
# 3d Array with it
np.random.seed(10)
np.random.randint(1,100,(3,2,4))

array([[[10, 16, 65, 29],
        [90, 94, 30,  9]],

       [[74,  1, 41, 37],
        [17, 12, 55, 89]],

       [[63, 34, 73, 79],
        [50, 52, 55, 78]]])

In [96]:
np.random.seed(10)
np.random.randint(1,100,(3,2,4))

array([[[10, 16, 65, 29],
        [90, 94, 30,  9]],

       [[74,  1, 41, 37],
        [17, 12, 55, 89]],

       [[63, 34, 73, 79],
        [50, 52, 55, 78]]])

In [97]:
np.random.rand(3)

array([0.13145815, 0.41366737, 0.77872881])

In [98]:
np.random.rand(3,3)

array([[0.58390137, 0.18263144, 0.82608225],
       [0.10540183, 0.28357668, 0.06556327],
       [0.05644419, 0.76545582, 0.01178803]])

In [99]:
np.random.randn(3)

array([-1.58494101,  1.05535316, -1.92657911])

In [101]:
x=[2,5,2,80,31]
np.random.choice(x)

2